START_BALANCE = 10000.0

POSITION_SIZE = 1000.0
MAX_POSITIONS = 3

TP_PCT = 0.003
SL_PCT = 0.002

REAL_ORDER_ENABLED = False
API_ORDER_ENABLED = False
AUTO_REAL_ORDER_ENABLED = False

MODE = "PAPER_ONLY"